services:
  gateway:
    environment:
      OPA_SERVICE_URL: http://opa:8181

  opa:
    image: docker.io/openpolicyagent/opa:1.17.1
    command: ["run", "--server", "--log-level=error", "--authorization=basic", "--v0-compatible", "--config-file", "/etc/opa/config.yml", "file:/etc/opa/system.rego", "file:/var/opa/store"]
    volumes:
      - ./config/opa:/etc/opa:ro
      - ./config/app/rego:/var/opa/store:ro
