services:
  rabbitmq:
    image: docker.io/library/rabbitmq:4.3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      start_period: 1m
    volumes:
      - rabbitmq_data:/var/lib/rabbitmw:rw

  rabbitmq-bootstrap:
    image: ghcr.io/xenit-eu/kubectl
    command: ["bash", "-c", "/tmp/rabbitmq/setup.sh"]
    environment:
      RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
    volumes:
      - ./bootstrap/rabbitmq:/tmp/rabbitmq:ro
    depends_on:
      rabbitmq:
        condition: service_healthy

  app-api:
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD

volumes:
  rabbitmq_data:
