services:
  tokenmonger:
    image: ghcr.io/xenit-eu/contentgrid-tokenmonger:SNAPSHOT
    ports:
      - "8081:8080"
    environment:
      SPRING_CONFIG_IMPORT: file:/etc/tokenmonger/config/application.yml
      TOKENMONGER_HOST: "http://${DOCKER_HOST_IP:-172.17.0.1}:8081"
      CONTENTGRID_TOKENMONGER_USERAPPLICATIONACCESS_JWKSETURI: "http://gateway:8081/actuator/jwks/authentication"
    volumes:
      - ./config/tokenmonger:/etc/tokenmonger/config:ro
      - tokenmonger_keys:/etc/tokenmonger/keys:ro
    depends_on:
      gateway:
        condition: service_started
      tokenmonger-bootstrap:
        condition: service_completed_successfully
        restart: true

  tokenmonger-bootstrap:
    image: ghcr.io/xenit-eu/kubectl
    volumes:
      - ./bootstrap/tokenmonger:/bootstrap:ro
      - tokenmonger_keys:/etc/tokenmonger/secrets:rw
    working_dir: /etc/tokenmonger/secrets
    command: ["/bin/bash", "-c", "/bootstrap/gen-keys.sh"]
volumes:
  tokenmonger_keys:
