services:
  gateway:
    image: ghcr.io/xenit-eu/contentgrid-gateway:SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_IMPORT: file:/etc/gateway/config/application.yml,/etc/gateway/config/app.yml
      TOKENMONGER_HOST: "http://${DOCKER_HOST_IP:-172.17.0.1}:8081"
      DOCKER_HOST_IP: "${DOCKER_HOST_IP:-172.17.0.1}"
    volumes:
      - ./config/gateway:/etc/gateway/config:ro
      - gateway_keys:/etc/gateway/keys:ro
    depends_on:
      gateway-bootstrap:
        condition: service_completed_successfully
        required: true
        restart: true
  gateway-bootstrap:
    image: ghcr.io/xenit-eu/kubectl
    volumes:
      - ./bootstrap/gateway:/bootstrap:ro
      - gateway_keys:/etc/gateway/secrets:rw
    working_dir: /etc/gateway/secrets
    command: ["/bin/bash", "-c", "/bootstrap/gen-keys.sh"]

  app-api:
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: http://gateway:8081/actuator/jwks/apps
    depends_on:
      gateway:
        condition: service_started
volumes:
  gateway_keys:
