apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: contentgrid-runtime
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: runtime-platform-config
  namespace: {{ .Values.userapps.namespace }}
data:
  server.forward-headers-strategy: native
  server.tomcat.remoteip.internal-proxies: 100\.64\.\d{1,3}\.\d{1,3}
  management.endpoints.web.exposure.include: '*'
  management.server.port: '8081'
  spring.datasource.hikari.minimum-idle: "0"
{{- if .Values.rabbitmq.enabled }}
  spring.rabbitmq.host: {{ include "rabbitmq_host" .}}
  spring.rabbitmq.username: apps
  spring.rabbitmq.template.exchange: 'contentgrid.apps'
  contentgrid.audit.messaging.source: "https://{{ required "userapps.defaultDomainSuffix is required" .Values.userapps.defaultDomainSuffix }}"
  contentgrid.audit.messaging.destination: 'contentgrid.audit'
{{- end }}
  # The trailing dot is on purpose, we don't want any DNS search domains to apply when the direct name can not be resolved
  spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://gateway-jwks.{{ .Release.Namespace }}.svc.cluster.local./actuator/jwks/apps
