# Sets up a service account used for the management platform to deploy ContentGrid applications to this runtime platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/part-of: contentgrid-runtime
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: contentgrid-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/part-of: contentgrid-runtime
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: contentgrid-management
  namespace: {{ .Values.userapps.namespace }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
    - services
    - configmaps
  verbs:
    - "*"
- apiGroups:
    - "apps"
  resources:
    - deployments
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/part-of: contentgrid-runtime
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: contentgrid-management
  namespace: {{ .Values.userapps.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contentgrid-management
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: contentgrid-management
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: contentgrid-runtime
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/service-account.name: contentgrid-management
  name: contentgrid-management-sa
type: kubernetes.io/service-account-token
