---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker.xenit.eu
spec:
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: docker.xenit.eu
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.externalSecrets.pullSecrets.docker_xenit_eu.key }}