services:
  app-api:
    image: ghcr.io/xenit-eu/contentgrid-appserver:SNAPSHOT@sha256:ff510a08164ec0bd313f52957483ba5e31060feabab6ace9fac2a62318d0f18f
    environment:
      SPRING_CONFIG_IMPORT: file:/etc/app/config/application.yml
      SPRING_DATASOURCE_URL: jdbc:postgresql://app-database/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: http://gateway:8081/actuator/jwks/apps

      CONTENTGRID_EVENTS_WEBHOOKCONFIGURL: http://app-api:8081/actuator/webhooks
      CONTENTGRID_APPSERVER_BLUEPRINTARTIFACT_LOCATION: file:/etc/app/config
      CONTENTGRID_SYSTEM_APPLICATIONID: app1
      CONTENTGRID_SYSTEM_DEPLOYMENTID: depl1

    volumes:
      - ./config/app:/etc/app/config:ro
    depends_on:
      gateway:
        condition: service_started
      app-database:
        condition: service_started

  app-database:
    image: docker.io/library/postgres:18
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  navigator:
    image: ghcr.io/xenit-eu/contentgrid-navigator:main@sha256:867124bb2427835ac89a3ffe321463624b2a2fb95965707d05bc282760283dc4
    ports:
      - "8085:8080"
    environment:
      API_BASE_URL: http://localhost:8080
      OIDC_AUTHORITY: http://${DOCKER_HOST_IP:-172.17.0.1}:8082/realms/cg-holmes
      OIDC_CLIENT_ID: navigator

  test-webhook-receiver:
    image: ghcr.io/mendhak/http-https-echo:41
    environment:
      HTTP_PORT: 8888
      JWT_HEADER: contentgrid-signature
      ECHO_BACK_TO_CLIENT: "false"
    ports:
      - "8888:8888"
