ingressClassName: haproxy

#additionalCAs: |
#  -----BEGIN CERTIFICATE-----
#  ...
#  -----END CERTIFICATE-----

gateway:
  image: ghcr.io/xenit-eu/contentgrid-gateway:SNAPSHOT@sha256:84c13032a1b147de72266ebd85b3450ebcf6a6c550086bec8da930754a4d071d
  debug: false
  accessLogging: false
#  maxInitialLineLength: 4096  # increase to allow longer URLs (e.g. many query parameters)
#  resourceLimits:
#    cpu: "1000m"
#    memory: "1Gi"
#  resourceRequests:
#    cpu: "100m"
#    memory: "512Mi"
tokenmonger:
  image: ghcr.io/xenit-eu/contentgrid-tokenmonger:SNAPSHOT@sha256:0d629e31591397a01058033691e01d7f6fc4c9af3b6637bd2c0aa48aa685c7ec
  host: ~
  protocol: https
  debug: false
opa:
  image: docker.io/openpolicyagent/opa:1.15.2
solon:
  image: ghcr.io/xenit-eu/contentgrid-solon:SNAPSHOT@sha256:159e859c6cb78ce8c8b39b20a64948096c508e2fc8bb81471e75ddee38f453f7
  debug: false
slingshot:
  image: ghcr.io/xenit-eu/contentgrid-slingshot:SNAPSHOT@sha256:0c4334a2384a5d6efdde10793923c387ef0d91319c20436e2cef26f8602a8756
  debug: false
pathfinder:
  image: ghcr.io/xenit-eu/contentgrid-pathfinder:SNAPSHOT@sha256:e69d6aa04bf7234adf97b7c6bd94680b4aa6a8b8628a2066f153fb0979bf537e
  debug: false
liaison:
  image: ghcr.io/xenit-eu/contentgrid-liaison:SNAPSHOT@sha256:7bff35ec76ff3a0862ca4df32e67fcf9456bf694cae686edf6221910c2fe8268
  debug: false
navigator:
  image: ghcr.io/xenit-eu/contentgrid-navigator:main@sha256:00ee7012452ca0a50e71b715f2d5a68b497609039c9183fcc795140cfdfd97fd
surveyor:
  prometheus:
    image: docker.io/prom/prometheus:latest@sha256:4a61322ac1103a0e3aea2a61ef1718422a48fa046441f299d71e660a3bc71ae9
  pegman:
    image: ghcr.io/xenit-eu/contentgrid-surveyor-pegman:SNAPSHOT@sha256:e0394661a2158f8de6c5fbf63e048c163ad70c5c72397ba659ff5d062b219cb4
    host: ~
    debug: false
    extraConfig: |
      {{- with .Values.surveyor.pegman.scaleway }}
      surveyor.systems.prometheus.scaleway-metrics.name: runtime
      surveyor.systems.prometheus.scaleway-metrics.type: scaleway:prometheus
      surveyor.systems.prometheus.scaleway-metrics.url: https://metrics.cockpit.{{ .region }}.scw.cloud/prometheus
      surveyor.systems.prometheus.scaleway-metrics.headers.x-datasource: product

      surveyor.systems.prometheus.scaleway-logs.name: runtime
      surveyor.systems.prometheus.scaleway-logs.type: scaleway:loki
      surveyor.systems.prometheus.scaleway-logs.url: https://logs.cockpit.{{ .region }}.scw.cloud/loki
      surveyor.systems.prometheus.scaleway-logs.headers.x-datasource: product
      {{- end }}
    extraCiliumNetworkPolicyEgress: |
      {{- with .Values.surveyor.pegman.scaleway }}
      - toFQDNs:
          - matchName: "metrics.cockpit.{{ .region }}.scw.cloud"
          - matchName: "logs.cockpit.{{ .region }}.scw.cloud"
        toPorts:
          - ports:
              - port: "443"
                protocol: TCP
      {{- end }}
    systems:
      secretKey: name:surveyor-scaleway-token
#    scaleway:
#      region: fr-par
#      token:
  postgresExporter:
    image: ghcr.io/xenit-eu/contentgrid-surveyor-exporter-postgres:SNAPSHOT@sha256:8e68a03d60e5c152c727d61239bf8e7891ac1ee606b949514360244839191132
    debug: false
  cgappApiExporter:
    image: ghcr.io/xenit-eu/contentgrid-surveyor-exporter-cgapp-api:SNAPSHOT@sha256:cb421574ce8defd4d0acc2fed36c895e120dd896bb28fa4e8ab68d1cb710d3be
    debug: false

userapps:
  namespace: default
  ingressClassName: haproxy
  forwardHeadersTrustedIp: '100\.64\.\d{1,3}\.\d{1,3}'
  #defaultDomainSuffix: ~
  #database:
    #- ip: ~
    #  port: ~

development: true

jobs:
  resourceLimits:
    cpu: 200m
    memory: 512Mi

keycloak:
  host: ~
  protocol: https
  db:
    secretKey: path:/rtp/keycloak-db-password
  extraRealms: {}

certificates:
  defaultIssuer: letsencrypt-production
#  issuers:
#    my-issuer:
#      acme:
#        email: ~
#        server: ~
#        externalAccountBinding:
#          keyId: ~
#          secretName: ~

pods:
#  nodeSelector:
#    example.com/node-role: contentgrid
#  tolerations:
#    - key: "example.com/node-role"
#      operator: "Equal"
#      value: "contentgrid"


keycloakx:
  enabled: true
  image:
    # Explicitly configuring the repository allows renovatebot to send image update PRs
    repository: quay.io/keycloak/keycloak
    tag: 26.5.6
  fullnameOverride: keycloak # this is used for the name of the service that we use in the ingress
  replicas: 1
  args:
    - 'start'
    - '--hostname-strict=false'
    - '--import-realm'
  extraEnv: |
    - name: JAVA_OPTS_APPEND
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=50.0
        -Djava.awt.headless=true
  proxy:
    mode: xforwarded
  database:
    vendor: postgres
    hostname: ~
    port: ~
    database: keycloak
    username: keycloak
    existingSecret: keycloak-database
  http:
    relativePath: /
  service:
    httpPort: 8080
  extraInitContainers: |
    - name: theme-provider
      image: ghcr.io/xenit-eu/contentgrid-keycloak-themes:0.0.1-snapshot
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /contentgrid-keycloak-themes/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme

  extraVolumeMounts: |
    - name: theme
      mountPath: /opt/keycloak/providers/
    - name: realms-import
      mountPath: /opt/keycloak/data/import/
  extraVolumes: |
    - name: theme
      emptyDir: {}
    - name: realms-import
      configMap:
        name: keycloak-realms-import

rabbitmq:
  enabled: true
  image:
    repository: docker.io/rabbitmq
    tag: '4.2'
    digest: sha256:0ea64c69ef2ced52e7188c6db826152d42f78e448433ed8b4e570170c427a437
  fullnameOverride: rabbitmq
  resources:
    limits:
      cpu: 750m
      memory: 1536Mi
      ephemeral-storage: 2Gi
  podLabels:
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
