ingressClassName: nginx

gateway:
  image: ghcr.io/xenit-eu/contentgrid-gateway:SNAPSHOT@sha256:736716be045fb4709a72aa8fb9854a8bae0cb85b7dbe4e2638d0db0ab2df29db
  debug: false
tokenmonger:
  image: ghcr.io/xenit-eu/contentgrid-tokenmonger:SNAPSHOT@sha256:644e5b14668a982504f1cf2213217ef5bb00cf533eae2213b2c5071fe8db46b9
  host: ~
  protocol: https
  debug: false
opa:
  image: docker.io/openpolicyagent/opa:0.70.0
solon:
  image: ghcr.io/xenit-eu/contentgrid-solon:SNAPSHOT@sha256:27f040a3aa158b11e014fc7ee97624cd95a5d102afd8c0ee7f401354f5946357
  debug: false
slingshot:
  image: ghcr.io/xenit-eu/contentgrid-slingshot:SNAPSHOT@sha256:fcb77f96c7829a3cbc09b2bafa8204da63de234d2afdf15a5a3f2ea61a0b07ac
  debug: false
pathfinder:
  image: ghcr.io/xenit-eu/contentgrid-pathfinder:SNAPSHOT@sha256:6f80ec48deeb9da77cce0ef439a0c19452ef328ecfa4684143b4c69bc6123407
  debug: false
liaison:
  image: ghcr.io/xenit-eu/contentgrid-liaison:SNAPSHOT@sha256:21b5e6e6b0ef874ba3632a5d066bb6f1dd78e7a40abf1717d1a0899d769b58c0
  debug: false
navigator:
  image: ghcr.io/xenit-eu/contentgrid-navigator:main@sha256:565dec5df84ffaaa2ff853b5029e18ee484b35f12fa74a1f8000290fa9a3d280
surveyor:
  prometheus:
    image: docker.io/prom/prometheus:latest@sha256:63805ebb8d2b3920190daf1cb14a60871b16fd38bed42b857a3182bc621f4996
  pegman:
    image: ghcr.io/xenit-eu/contentgrid-surveyor-pegman:SNAPSHOT@sha256:b0590ad3c1dd562eb639afe1253e74c8436fc58a1249e61b0728a80362b45ac6
    host: ~
    debug: false
    extraConfig: |
      {{- with .Values.surveyor.pegman.scaleway }}
      surveyor.systems.prometheus.scaleway-metrics.name: runtime
      surveyor.systems.prometheus.scaleway-metrics.type: scaleway:prometheus
      surveyor.systems.prometheus.scaleway-metrics.url: https://metrics.cockpit.{{ .region }}.scw.cloud/prometheus
      surveyor.systems.prometheus.scaleway-metrics.headers.x-datasource: product

      surveyor.systems.prometheus.scaleway-logs.name: runtime
      surveyor.systems.prometheus.scaleway-logs.type: scaleway:loki
      surveyor.systems.prometheus.scaleway-logs.url: https://logs.cockpit.{{ .region }}.scw.cloud/loki
      surveyor.systems.prometheus.scaleway-logs.headers.x-datasource: product
      {{- end }}
    extraCiliumNetworkPolicyEgress: |
      {{- with .Values.surveyor.pegman.scaleway }}
      - toFQDNs:
          - matchName: "metrics.cockpit.{{ .region }}.scw.cloud"
          - matchName: "logs.cockpit.{{ .region }}.scw.cloud"
        toPorts:
          - ports:
              - port: "443"
                protocol: TCP
      {{- end }}
    systems:
      secretKey: name:surveyor-scaleway-token
#    scaleway:
#      region: fr-par
#      token:
  postgresExporter:
    image: ghcr.io/xenit-eu/contentgrid-surveyor-exporter-postgres:SNAPSHOT@sha256:29be96de3e9bc1f98c8f29ed2840cdd685787e8ffffd6320d08a456ba68a40fa
    debug: false
  cgappApiExporter:
    image: ghcr.io/xenit-eu/contentgrid-surveyor-exporter-cgapp-api:SNAPSHOT@sha256:d9f38066aa476b65692f14c1821d69bf26175f8dec7ac4748f48e455e04244d2
    debug: false

userapps:
  namespace: default
  ingressClassName: nginx
  #defaultDomainSuffix: ~
  #database:
    #- ip: ~
    #  port: ~

development: true

keycloak:
  host: ~
  protocol: https
  db:
    secretKey: path:/rtp/keycloak-db-password
  extraRealms: {}

certificates:
  defaultIssuer: letsencrypt-production
#  issuers:
#    my-issuer:
#      acme:
#        email: ~
#        server: ~
#        externalAccountBinding:
#          keyId: ~
#          secretName: ~


keycloakx:
  enabled: true
  image:
    # Explicitly configuring the repository allows renovatebot to send image update PRs
    repository: quay.io/keycloak/keycloak
    tag: 26.3.3
  fullnameOverride: keycloak # this is used for the name of the service that we use in the ingress
  replicas: 1
  args:
    - 'start'
    - '--hostname-strict=false'
    - '--import-realm'
  extraEnv: |
    - name: JAVA_OPTS_APPEND
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=50.0
        -Djava.awt.headless=true
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  proxy:
    mode: xforwarded
  database:
    vendor: postgres
    hostname: ~
    port: ~
    database: keycloak
    username: keycloak
    existingSecret: keycloak-database
  http:
    relativePath: /
  service:
    httpPort: 8080
  extraInitContainers: |
    - name: theme-provider
      image: ghcr.io/xenit-eu/contentgrid-keycloak-themes:0.0.1-snapshot
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /contentgrid-keycloak-themes/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme

  extraVolumeMounts: |
    - name: theme
      mountPath: /opt/keycloak/providers/
    - name: realms-import
      mountPath: /opt/keycloak/data/import/
  extraVolumes: |
    - name: theme
      emptyDir: {}
    - name: realms-import
      configMap:
        name: keycloak-realms-import

rabbitmq:
  enabled: true
  fullnameOverride: rabbitmq
  enableServiceLinks: false
  resourcesPreset: medium
  auth:
    existingPasswordSecret: rabbitmq
    existingErlangSecret: rabbitmq
  networkPolicy:
    enabled: true
  metrics:
    enabled: true
  volumePermissions:
    enabled: true
  commonLabels:
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
