gateway:
  image: ghcr.io/xenit-eu/contentgrid-gateway:SNAPSHOT@sha256:462a10bfde63125d6f9ef20fe2f110b84a832123a72c14888914bb40018550bf
tokenmonger:
  image: ghcr.io/xenit-eu/contentgrid-tokenmonger:SNAPSHOT@sha256:cbf1200686cb824d4322824e46c37b1750d7982a1ef24e2b5152b77aa26edbe6
  host: ~
opa:
  image: docker.io/openpolicyagent/opa:0.58.0-rootless
solon:
  image: ghcr.io/xenit-eu/contentgrid-solon:SNAPSHOT@sha256:49b8196db62d88611f0778f90d8d3d32dddde8931911c167ab4a13106a9b0dd9
slingshot:
  image: ghcr.io/xenit-eu/contentgrid-slingshot:SNAPSHOT@sha256:9e4beb881324a2599c85e61e395e7a546b83e11e8fd260507684ed441b581687
pathfinder:
  image: ghcr.io/xenit-eu/contentgrid-pathfinder:SNAPSHOT@sha256:3bdc80802fa3efa157159349313308482d1905a6dab36eae8ba4fa6ee2a76630
liaison:
  image: ghcr.io/xenit-eu/contentgrid-liaison:SNAPSHOT@sha256:2eaf51aca6a077d3ef6c4414096a2f49cfa9f69fc75863309f69f4e02e1aa5de
navigator:
  image: ghcr.io/xenit-eu/contentgrid-navigator:main@sha256:5f54a4986db682c6322286ba22db6c756c9142eff1a05e610313e2e6d73cf5e3 
surveyor:
  prometheus:
    image: docker.io/prom/prometheus:latest@sha256:f6639335d34a77d9d9db382b92eeb7fc00934be8eae81dbc03b31cfe90411a94
  pegman:
    image: ghcr.io/xenit-eu/contentgrid-surveyor-pegman:SNAPSHOT@sha256:4ad1b7541cdf55f94c6d491b883bea95d2f833c40f8042827e8c42b22b5d6432
    host: ~
    extraConfig: |
      {{- with .Values.surveyor.pegman.scaleway }}
      surveyor.systems.prometheus.scaleway-metrics.name: runtime
      surveyor.systems.prometheus.scaleway-metrics.type: scaleway:prometheus
      surveyor.systems.prometheus.scaleway-metrics.url: https://metrics.cockpit.{{ .region }}.scw.cloud/prometheus
      surveyor.systems.prometheus.scaleway-metrics.headers.x-datasource: product

      surveyor.systems.prometheus.scaleway-logs.name: runtime
      surveyor.systems.prometheus.scaleway-logs.type: scaleway:loki
      surveyor.systems.prometheus.scaleway-logs.url: https://logs.cockpit.{{ .region }}.scw.cloud/loki
      surveyor.systems.prometheus.scaleway-logs.headers.x-datasource: product
      {{- end }}
    extraSecrets: |
      {{- with .Values.surveyor.pegman.scaleway }}
      surveyor.systems.prometheus.scaleway-metrics.headers.x-token: {{ .token | b64enc }}
      surveyor.systems.prometheus.scaleway-logs.headers.x-token: {{ .token | b64enc }}
      {{- end }}
    extraCiliumNetworkPolicyEgress: |
      {{- with .Values.surveyor.pegman.scaleway }}
      - toFQDNs:
          - matchName: "metrics.cockpit.{{ .region }}.scw.cloud"
          - matchName: "logs.cockpit.{{ .region }}.scw.cloud"
        toPorts:
          - ports:
              - port: "443"
                protocol: TCP
      {{- end }}
#    scaleway:
#      region: fr-par
#      token:
  postgresExporter:
    image: ghcr.io/xenit-eu/contentgrid-surveyor-exporter-postgres:SNAPSHOT@sha256:b3045ed4ba720e15079c3d0cb2c0c398218a7034fc865a82c18b7718aec0c883
  cgappApiExporter:
    image: ghcr.io/xenit-eu/contentgrid-surveyor-exporter-cgapp-api:SNAPSHOT@sha256:218a600d78e90a1b9591217973da8d834a47ade5acd353f5afc36b7b69286366

userapps:
  namespace: default
  ingressClassName: nginx
  #defaultDomainSuffix: ~
  #database:
    #- ip: ~
    #  port: ~

development: true

keycloak:
  host: ~

certificates:
  defaultIssuer: letsencrypt-production
#  issuers:
#    my-issuer:
#      acme:
#        email: ~
#        server: ~
#        externalAccountBinding:
#          keyId: ~
#          secretName: ~


keycloakx:
  enabled: true
  image:
    # Explicitly configuring the repository allows renovatebot to send image update PRs
    repository: quay.io/keycloak/keycloak
    tag: 25.0.6
  fullnameOverride: keycloak # this is used for the name of the service that we use in the ingress
  replicas: 1
  args:
    - 'start'
    - '--hostname-strict=false'
    - '--import-realm'
  extraEnv: |
    - name: JAVA_OPTS_APPEND
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=50.0
        -Djava.awt.headless=true
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  proxy:
    mode: xforwarded
  database:
    vendor: postgres
    hostname: ~
    port: ~
    database: keycloak
    username: keycloak
    existingSecret: keycloak-database
  http:
    relativePath: /
  service:
    httpPort: 8080
  extraPorts:
    - containerPort: 7800
  extraInitContainers: |
    - name: theme-provider
      image: ghcr.io/xenit-eu/contentgrid-keycloak-themes:0.0.1-snapshot
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /contentgrid-keycloak-themes/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme

  extraVolumeMounts: |
    - name: theme
      mountPath: /opt/keycloak/providers/
    - name: realms-import
      mountPath: /opt/keycloak/data/import/
  extraVolumes: |
    - name: theme
      emptyDir: {}
    - name: realms-import
      configMap:
        name: keycloak-realms-import

rabbitmq:
  fullnameOverride: rabbitmq
  enableServiceLinks: false
  resourcesPreset: medium
  auth:
    existingPasswordSecret: rabbitmq
    existingErlangSecret: rabbitmq
  networkPolicy:
    enabled: true
  metrics:
    enabled: true
  volumePermissions:
    enabled: true
  commonLabels:
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
