---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/component: proxy
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        prometheus.io/path: actuator/prometheus
        prometheus.io/port: '8081'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: gateway
          image: {{ .Values.gateway.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
          env:
            - name: 'OPA_SERVICE_URL'
              value: 'http://opa-service:8181'
            - name: SERVICEDISCOVERY_ENABLED
              value: 'true'
            - name: SERVICEDISCOVERY_NAMESPACE
              value: '{{ .Values.userapps.namespace }}'
            - name: 'SPRING_CONFIG_IMPORT'
              value: 'file:/etc/gateway/application.yml'
          volumeMounts:
            - name: gateway-config-volume
              mountPath: /etc/gateway/
              readOnly: true
      volumes:
        - name: gateway-config-volume
          configMap:
            name: gateway-config
      serviceAccountName: contentgrid-gateway
      automountServiceAccountToken: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yml: |
    management:
      server:
        port: 8081
      endpoints:
        web:
          exposure:
            include: '*'
    contentgrid:
      gateway:
        runtime-platform:
          enabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - port: 8080
      targetPort: http
      name: http
    - port: 8081
      targetPort: management
      name: management
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contentgrid-gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: contentgrid-gateway
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: contentgrid-gateway
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contentgrid-gateway
subjects:
- kind: ServiceAccount
  name: contentgrid-gateway
  namespace: {{ .Release.Namespace }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gateway-to-apiserver
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  egress:
    - toEntities:
        - kube-apiserver
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-to-opa
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: openpolicyagent
              app.kubernetes.io/component: authorization
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-to-apps
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  egress:
    - to:
        - namespaceSelector:
            matchLabels: {}
          podSelector:
            matchLabels:
              app.contentgrid.com/service-type: api
      ports:
        - port: 8080 # Access to public port only
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gateway-to-auth
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  egress:
    - toFQDNs:
        - matchName: "auth.contentgrid.com"
        - matchName: "{{ .Values.keycloak.host }}"
      toPorts:
        - ports:
            - port: "443"
