apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-auth-pem
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
data:
  auth.pem: |-
{{ .Files.Get "files/auth.pem" | indent 4 }}
  type: "ca-certificates"
