---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  replicas: 1
  template:
    metadata:
      labels:
        {{ if .Values.development -}}
        date: "{{ now | unixEpoch }}"
        {{- end }}
        app.kubernetes.io/name: gateway
        app.kubernetes.io/component: proxy
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: gateway
          image: {{ .Values.gateway.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - containerPort: 80
          env:
            - name: 'OPA_SERVICE_URL'
              value: 'http://opa-service:8181'
            - name: SERVICEDISCOVERY_ENABLED
              value: 'true'
            - name: SERVICEDISCOVERY_NAMESPACE
              value: '{{ .Values.userapps.namespace }}'
      serviceAccountName: contentgrid-gateway
      automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
      app.kubernetes.io/name: gateway
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-mgmt-service
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contentgrid-gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: contentgrid-gateway
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: contentgrid-gateway
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contentgrid-gateway
subjects:
- kind: ServiceAccount
  name: contentgrid-gateway
  namespace: {{ .Release.Namespace }}
