---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/component: proxy
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        prometheus.io/path: actuator/prometheus
        prometheus.io/port: '8081'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: gateway
          image: {{ .Values.gateway.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081
          {{- include "contentgrid.probes" "management" | indent 10 }}
          env:
            - name: 'OPA_SERVICE_URL'
              value: 'http://opa-service:8181'
            - name: SERVICEDISCOVERY_ENABLED
              value: 'true'
            - name: SERVICEDISCOVERY_NAMESPACE
              value: '{{ .Values.userapps.namespace }}'
            - name: 'TOKENMONGER_HOST'
              value: '{{ .Values.tokenmonger.host }}'
            - name: 'SPRING_CONFIG_IMPORT'
              value: 'file:/etc/gateway/application.yml'
          volumeMounts:
            - name: gateway-config-volume
              mountPath: /etc/gateway/
              readOnly: true
            - name: jwt-apps-keys
              mountPath: /etc/gateway/keys/jwt-apps
              readOnly: true
            - name: jwt-authentication-keys
              mountPath: /etc/gateway/keys/jwt-authentication
              readOnly: true
            - name: jwt-authentication-encryption-keys
              mountPath: /etc/gateway/keys/jwt-authentication-encryption
              readOnly: true
      volumes:
        - name: gateway-config-volume
          configMap:
            name: gateway-config
        - name: jwt-apps-keys
          secret:
            secretName: gateway-jwt-apps-keys # secret created by templates/bootstrap/gateway.yml
        - name: jwt-authentication-keys
          secret:
            secretName: gateway-jwt-authentication-keys # secret created by templates/bootstrap/gateway.yml
        - name: jwt-authentication-encryption-keys
          secret:
            secretName: gateway-jwt-authentication-encryption-keys # secret created by templates/bootstrap/gateway.yml
      enableServiceLinks: false
      serviceAccountName: contentgrid-gateway
      automountServiceAccountToken: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yml: |
    management:
      server:
        port: 8081
      endpoints:
        web:
          exposure:
            include: '*'
    contentgrid:
      configuration:
        discovery:
          kubernetes:
            namespace: "${servicediscovery.namespace}"
      gateway:
        runtime-platform:
          enabled: true
          external-issuers:
            extension-delegation:
              issuer: https://${tokenmonger.host}/authentication/delegated
              jwk-set-uri: https://${tokenmonger.host}/authentication/delegated/jwks
            extension-system:
              issuer: https://${tokenmonger.host}/authentication/system
              jwk-set-uri: https://${tokenmonger.host}/authentication/system/jwks
          endpoints:
            authentication:
              uri: http://tokenmonger:8080
              authorization: authenticated
              encryption:
                active-keys: file:/etc/gateway/keys/jwt-authentication-encryption/active-*.bin
                all-keys: file:/etc/gateway/keys/jwt-authentication-encryption/*.bin
        jwt:
          signers:
            apps:
              active-keys: file:/etc/gateway/keys/jwt-apps/active-*.pem
              all-keys: file:/etc/gateway/keys/jwt-apps/*.pem
            authentication:
              active-keys: file:/etc/gateway/keys/jwt-authentication/active-*.pem
              all-keys: file:/etc/gateway/keys/jwt-authentication/*.pem
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - port: 8080
      targetPort: http
      name: http
    - port: 8081
      targetPort: management
      name: management
---
# This is a separate service, so we can later switch away from
# communicating directly with the gateway management port,
# without restarting all applications
apiVersion: v1
kind: Service
metadata:
  name: gateway-jwks
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - port: 80
      targetPort: management
      name: jwks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contentgrid-gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gateway-to-apiserver
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  egress:
    - toEntities:
        - kube-apiserver
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-to-opa
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: openpolicyagent
              app.kubernetes.io/component: authorization
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-to-apps
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  egress:
    - to:
        - namespaceSelector:
            matchLabels: {}
          podSelector:
            matchLabels:
              app.contentgrid.com/service-type: api
      ports:
        - port: 8080 # Access to public port only
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-to-tokenmonger
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: tokenmonger
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-jwks-from-apps
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  ingress:
    - from:
        - namespaceSelector:
            matchLabels: {}
          podSelector:
            matchLabels:
              app.contentgrid.com/service-type: api
      ports:
        - port: 8081 # Access to management port only
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-jwks-from-tokenmonger
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: tokenmonger
      ports:
        - port: 8081 # Access to management port only
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gateway-to-auth
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: proxy
  egress:
    - toFQDNs:
        - matchName: "auth.contentgrid.com"
        - matchName: "{{ .Values.keycloak.host }}"
        - matchName: "{{ .Values.tokenmonger.host }}"
      toPorts:
        - ports:
            - port: {{ if eq .Values.keycloak.protocol "http" }} "80" {{ else }} "443" {{ end }}
