{{ if .Values.keycloakx.enabled }}
# most keycloak stuff is in values.yml because this project depends on the codecentric keycloakx chart
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contentgrid-keycloak
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    {{- with .Values.certificates.defaultIssuer }}
    cert-manager.io/cluster-issuer: {{ . }}
    {{- end }}
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host: {{ .Values.keycloak.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-http
            port:
              number: 8080
  tls:
  - secretName: keycloak-tls
    hosts:
    - {{ .Values.keycloak.host }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realms-import
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "definitions/keycloak-realm-*.json").AsConfig | indent 2}}

{{- range $key, $value := .Values.keycloak.extraRealms }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: keycloakx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: keycloakx
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8443
    {{ range $.Values.keycloakx.extraPorts }}
    - protocol: {{ default "TCP" .protocol }}
      port: {{ .containerPort }}
    {{- end }}
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.keycloakx.database.hostname }}/24
    ports:
    - port: {{ .Values.keycloakx.database.port }}
      protocol: TCP
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 443
      protocol: TCP
  # This is for the infinispan cluster
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: keycloakx
    ports:
    - port: 7800
      protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: keycloak-to-smtp
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: keycloakx
  egress:
    - toFQDNs:
        - matchName: "smtp.tem.scw.cloud"
      toPorts:
        - ports:
            - port: "465"
              protocol: TCP
            - port: "2465"
              protocol: TCP
{{ end }}
---
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-database
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: contentgrid-runtime
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.keycloakx.database.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.keycloak.db.secretKey }}
