---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liaison
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: liaison
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/component: liaison
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
        app.kubernetes.io/component: liaison
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        prometheus.io/path: actuator/prometheus
        prometheus.io/port: '8081'
        prometheus.io/scrape: 'true'
        instrumentation.opentelemetry.io/inject-java: grafana-agent/grafana-instrumentation
    spec:
      containers:
        - name: liaison
          image: {{ .Values.liaison.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081
          {{ if not .Values.liaison.debug -}}
          {{- include "contentgrid.probes" "management" | indent 10 }}
          {{- end }}
          env:
            - name: 'SPRING_CONFIG_IMPORT'
              value: 'file:/etc/liaison/application.yml'
            {{ if .Values.liaison.debug -}}
            - name: 'JAVA_TOOL_OPTIONS'
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
            {{- end }}
          volumeMounts:
            - name: liaison-config-volume
              mountPath: /etc/liaison/
              readOnly: true
      volumes:
        - name: liaison-config-volume
          configMap:
            name: liaison-config
      enableServiceLinks: false
      serviceAccountName: liaison-serviceaccount
      automountServiceAccountToken: true
{{ include "nodeSelection" . | indent 6}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: liaison-config
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: liaison
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yml: |
    liaison:
        discovery:
            webapp:
                namespace: '{{ .Values.userapps.namespace }}'
                resync-interval-seconds: 300
            gateway:
                namespace: '{{ .Values.userapps.namespace }}'
                resync-interval-seconds: 300
        {{ if (.Values.liaison.renditions).uriTemplate -}}
        {{ with .Values.liaison.renditions.uriTemplate -}}
        additionalProperties.renditionUriTemplate: '{{ . }}'
        {{- end }}
        {{- end }}
        {{ if (.Values.liaison.extract).baseUrl -}}
        {{ with .Values.liaison.extract.baseUrl -}}
        additionalProperties.extractServiceBaseUrl: '{{ . }}'
        {{- end }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: liaison-service
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: liaison
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/component: liaison
  ports:
    - name: http
      port: 8080
      targetPort: http
      appProtocol: http
    - name: management
      port: 8081
      targetPort: management
      appProtocol: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: liaison-serviceaccount
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: liaison
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: liaison-role
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: liaison
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: liaison-rolebinding
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: liaison
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: liaison-role
subjects:
- kind: ServiceAccount
  name: liaison-serviceaccount
  namespace: {{ .Release.Namespace }}
---
{{/* NetworkPolicy liaison-to-apiserver */}}
{{- $policyLabels := (list
    "app.kubernetes.io/name: webapp"
    "app.kubernetes.io/component: liaison"
    "app.kubernetes.io/part-of: contentgrid-runtimeplatform"
    ( printf "app.kubernetes.io/managed-by: %s" .Release.Service)
) | join "\n" | fromYaml -}}
{{- $selectorLabels := (list
    "app.kubernetes.io/name: webapp"
    "app.kubernetes.io/component: liaison"
) | join "\n" | fromYaml -}}
{{- template "contentgrid.apiserver-network-policy"
      dict
        "name" "liaison-to-apiserver"
        "policyLabels" $policyLabels
        "selectorLabels" $selectorLabels
        "rootScope" $ }}
