---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navigator
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: navigator
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/component: navigator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
        app.kubernetes.io/component: navigator
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: navigator
          image: {{ .Values.navigator.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: API_BASE_URL
              value: "https://app.contentgrid-poc.ethias.be"
            - name: OIDC_AUTHORITY
              value: https://auth.contentgrid-poc.ethias.be/realms/cg-f1aca8f5-6007-4080-a768-c5575a331e12
            - name: OIDC_CLIENT_ID
              value: contentgrid-webapp-bbbaa924-8b2a-46a1-b211-cf7e755898f8
      enableServiceLinks: false
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: navigator-service
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: navigator
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/component: navigator
  ports:
    - name: http
      port: 80
      targetPort: http
      appProtocol: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navigator-ingress
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: navigator
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  tls:
    - hosts:
        - navigator.contentgrid-poc.ethias.be
      secretName: keycloak-tls
  rules:
    - host: navigator.contentgrid-poc.ethias.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navigator-service
                port:
                  number: 80
