---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navigator
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: navigator
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/component: navigator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
        app.kubernetes.io/component: navigator
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: navigator
          image: {{ .Values.navigator.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

      enableServiceLinks: false
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: navigator-service
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: navigator
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/component: navigator
  ports:
    - name: http
      port: 80
      targetPort: http
      appProtocol: http
