---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openpolicyagent
  labels:
    app.kubernetes.io/name: openpolicyagent
    app.kubernetes.io/component: authorization
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openpolicyagent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openpolicyagent
        app.kubernetes.io/component: authorization
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: openpolicyagent
          image: {{ .Values.opa.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          args: [
            'run',
            '--server',
            '--log-format=json',
            '--log-level=error',
            '--authorization=basic',
            '--v0-compatible',
            '--config-file', '/config/config.yml',
            'file:/config/system.rego'
          ]
          ports:
            - name: http
              containerPort: 8181
          livenessProbe:
            httpGet:
              port: 8181
          readinessProbe:
            httpGet:
              path: /health?bundle=true
              port: 8181
          volumeMounts:
            - name: opa-config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: opa-config-volume
          configMap:
            name: opa-config
      enableServiceLinks: false
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: opa-service
  labels:
    app.kubernetes.io/name: openpolicyagent
    app.kubernetes.io/component: authorization
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: openpolicyagent
  ports:
    - port: 8181
      targetPort: 8181
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  labels:
    app.kubernetes.io/name: openpolicyagent
    app.kubernetes.io/component: authorization
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yml: |
    services:
      solon:
        url: 'http://solon-service.{{ .Release.Namespace }}.svc.cluster.local:8080'
    bundles:
      authz:
        service: solon
        resource: '/bundle.tar.gz'
        polling:
          min_delay_seconds: 5
          max_delay_seconds: 10
          long_polling_timeout_seconds: 20
    decision_logs:
      console: true
  system.rego: |
    package system.authz
    # Deny access by default.
    default allow := false
    # Allow checking policies via compile endpoint
    allow {
        input.method == "POST"
        input.path == ["v1", "compile"]
    }
    # Allow health checks
    allow {
        input.method == "GET"
        input.path == [""]
    }
    allow {
        input.method == "GET"
        input.path == ["health"]
    }
    # Allow prometheus metric collection
    allow {
        input.method == "GET"
        input.path == ["metrics"]
    }
---
{{ if .Capabilities.APIVersions.Has "cilium.io/v2" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: opa-to-solon
  labels:
    app.kubernetes.io/name: openpolicyagent
    app.kubernetes.io/component: authorization
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openpolicyagent
      app.kubernetes.io/component: authorization
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: solon
              app.kubernetes.io/component: solon
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: opa-from-gateway
  labels:
    app.kubernetes.io/name: openpolicyagent
    app.kubernetes.io/component: authorization
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openpolicyagent
      app.kubernetes.io/component: authorization
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gateway
              app.kubernetes.io/component: proxy
      ports:
        - port: 8181
{{ end }}