{{ if not (default false .Values.pathfinder.disabled) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathfinder
  labels:
    app.kubernetes.io/name: pathfinder
    app.kubernetes.io/component: pathfinder
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pathfinder
      app.kubernetes.io/component: pathfinder
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pathfinder
        app.kubernetes.io/component: pathfinder
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        prometheus.io/path: actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
        instrumentation.opentelemetry.io/inject-java: grafana-agent/grafana-instrumentation
    spec:
      containers:
        - name: pathfinder
          image: {{ .Values.pathfinder.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: management
              containerPort: 8080
          {{ if not .Values.pathfinder.debug -}}
          {{- include "contentgrid.probes" "management" | indent 10 }}
          {{- end }}
          env:
            - name: 'SPRING_CONFIG_IMPORT'
              value: 'file:/etc/pathfinder/application.yml'
            - name: 'SPRING_PROFILES_ACTIVE'
              value: 'api'
            {{ if .Values.pathfinder.debug -}}
            - name: 'JAVA_TOOL_OPTIONS'
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
            {{- end }}
          volumeMounts:
            - name: pathfinder-config-volume
              mountPath: /etc/pathfinder/
              readOnly: true
      volumes:
        - name: pathfinder-config-volume
          configMap:
            name: pathfinder-config
      enableServiceLinks: false
      serviceAccountName: pathfinder-serviceaccount
      automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathfinder-for-webapp
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: pathfinder
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/component: pathfinder
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
        app.kubernetes.io/component: pathfinder
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        prometheus.io/path: actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
        instrumentation.opentelemetry.io/inject-java: grafana-agent/grafana-instrumentation
    spec:
      containers:
        - name: pathfinder
          image: {{ .Values.pathfinder.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: management
              containerPort: 8080
          {{- include "contentgrid.probes" "management" | indent 10 }}
          env:
            - name: 'SPRING_CONFIG_IMPORT'
              value: 'file:/etc/pathfinder/application.yml'
            - name: 'SPRING_PROFILES_ACTIVE'
              value: 'webapp'
          volumeMounts:
            - name: pathfinder-config-volume
              mountPath: /etc/pathfinder/
              readOnly: true
      volumes:
        - name: pathfinder-config-volume
          configMap:
            name: pathfinder-config
      enableServiceLinks: false
      serviceAccountName: pathfinder-serviceaccount
      automountServiceAccountToken: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pathfinder-config
  labels:
    app.kubernetes.io/name: pathfinder
    app.kubernetes.io/component: pathfinder
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yml: |
    pathfinder:
        source:
            namespace: '{{ .Values.userapps.namespace }}'
        target:
            namespace: '{{ .Release.Namespace }}'
            {{- with .Values.userapps.ingressClassName }}
            ingress-class-name: '{{ . }}'
            {{- end }}
            copy-annotations:
                '[cert-manager.io/cluster-issuer]':
                    default-value: '{{ .Values.certificates.defaultIssuer }}'
                    acceptable-values:
                    {{- with .Values.certificates.defaultIssuer }}
                        - '{{ . }}'
                    {{- end }}
                    {{- range (keys (.Values.certificates.issuers | default dict) | sortAlpha) }}
                        - '{{ . }}'
                    {{- end }}
            {{- with .Values.userapps.defaultDomainSuffix }}
            tls:
                fallback-cn-hostname: 'managed-by.{{ . }}'
            {{- end }}
  application-api.yml: |
    pathfinder:
        source:
            labels:
                '[app.contentgrid.com/service-type]': gateway
        target:
            services:
                - path: /
                  pathType: Prefix
                  serviceName: gateway-service
                  servicePort: 8080
                - path: /.well-known/jwks.json
                  pathType: Exact
                  serviceName: slingshot-service
                  servicePortName: http
  application-webapp.yml: |
    pathfinder:
        source:
            labels:
                '[app.contentgrid.com/service-type]': webapp
        target:
            services:
                - path: /
                  pathType: Prefix
                  serviceName: navigator-service
                  servicePortName: http
                - path: /config.js
                  pathType: Exact
                  serviceName: liaison-service
                  servicePortName: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pathfinder-serviceaccount
  labels:
    app.kubernetes.io/name: pathfinder
    app.kubernetes.io/component: pathfinder
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pathfinder-role
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: pathfinder
    app.kubernetes.io/component: pathfinder
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pathfinder-rolebinding
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: pathfinder
    app.kubernetes.io/component: pathfinder
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pathfinder-role
subjects:
- kind: ServiceAccount
  name: pathfinder-serviceaccount
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pathfinder-role
  labels:
    app.kubernetes.io/name: pathfinder
    app.kubernetes.io/component: pathfinder
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pathfinder-rolebinding
  labels:
    app.kubernetes.io/name: pathfinder
    app.kubernetes.io/component: pathfinder
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pathfinder-role
subjects:
- kind: ServiceAccount
  name: pathfinder-serviceaccount
---
{{ if .Capabilities.APIVersions.Has "cilium.io/v2" }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pathfinder-to-apiserver
  labels:
    app.kubernetes.io/name: pathfinder
    app.kubernetes.io/component: pathfinder
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: pathfinder
  egress:
    - toEntities:
        - kube-apiserver
{{ end }}
{{ end }}