{{ if .Values.rabbitmq.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: rabbitmq-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/component: message-queue
      app.kubernetes.io/part-of: contentgrid-runtimeplatform
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/component: message-queue
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-erlang-cookie
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
            - containerPort: 9419
              name: metrics
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{ .Values.rabbitmq.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
    - port: 9419
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq-from-apps
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/component: message-queue
      app.kubernetes.io/part-of: contentgrid-runtimeplatform
  ingress:
    - from:
        - namespaceSelector:
            matchLabels: {}
          podSelector:
            matchLabels:
              app.contentgrid.com/service-type: api
      ports:
        - port: 5672
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq-from-slingshot
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/component: message-queue
      app.kubernetes.io/part-of: contentgrid-runtimeplatform
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: slingshot
              app.kubernetes.io/component: webhook-invoker
      ports:
        - port: 5672
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq-clustering
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/component: message-queue
      app.kubernetes.io/part-of: contentgrid-runtimeplatform
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: rabbitmq
              app.kubernetes.io/component: message-queue
              app.kubernetes.io/part-of: contentgrid-runtimeplatform
      # Allow all ports, because cilium does not support port ranges
      # See https://www.rabbitmq.com/clustering.html#ports
      # See https://docs.cilium.io/en/latest/network/kubernetes/policy/#networkpolicy-state
      #ports:
      #  - port: 4369
      #  - port: 6000
      #    endPort: 6500
      #  - port: 25672
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: rabbitmq
              app.kubernetes.io/component: message-queue
              app.kubernetes.io/part-of: contentgrid-runtimeplatform
      # Allow all ports, because cilium does not support port ranges
      # See https://www.rabbitmq.com/clustering.html#ports
      # See https://docs.cilium.io/en/latest/network/kubernetes/policy/#networkpolicy-state
      #ports:
      #  - port: 4369
      #  - port: 6000
      #    endPort: 6500
      #  - port: 25672
---
{{/* NetworkPolicy rabbitmq-to-apiserver */}}
{{- $policyLabels := (list
    "app.kubernetes.io/name: rabbitmq"
    "app.kubernetes.io/component: message-queue"
    "app.kubernetes.io/part-of: contentgrid-runtimeplatform"
    ( printf "app.kubernetes.io/managed-by: %s" .Release.Service)
) | join "\n" | fromYaml -}}
{{- $selectorLabels := (list
      "app.kubernetes.io/name: rabbitmq"
      "app.kubernetes.io/component: message-queue"
      "app.kubernetes.io/part-of: contentgrid-runtimeplatform"
) | join "\n" | fromYaml -}}
{{- template "contentgrid.apiserver-network-policy"
      dict
        "name" "rabbitmq-to-apiserver"
        "policyLabels" $policyLabels
        "selectorLabels" $selectorLabels
        "rootScope" $ }}
{{ end }}
