---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slingshot
  labels:
    app.kubernetes.io/name: slingshot
    app.kubernetes.io/component: webhook-invoker
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: slingshot
  replicas: 1
  template:
    metadata:
      labels:
        {{ if .Values.development -}}
        date: "{{ now | unixEpoch }}"
        {{- end }}
        app.kubernetes.io/name: slingshot
        app.kubernetes.io/component: webhook-invoker
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: slingshot
          image: {{ .Values.slingshot.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - containerPort: 80
          env:
            - name: 'SPRING_CONFIG_IMPORT'
              value: 'file:/etc/slingshot/application.yml'
          volumeMounts:
            - name: slingshot-config-volume
              mountPath: /etc/slingshot/
              readOnly: true
      volumes:
        - name: slingshot-config-volume
          configMap:
            name: slingshot-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slingshot-config
  labels:
    app.kubernetes.io/name: slingshot
    app.kubernetes.io/component: webhook-invoker
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yml: |
    spring:
      rabbitmq:
        host: rabbitmq-service
---
apiVersion: v1
kind: Service
metadata:
  name: slingshot-service
  labels:
    app.kubernetes.io/name: slingshot
    app.kubernetes.io/component: webhook-invoker
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
      app.kubernetes.io/name: slingshot
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: slingshot-mgmt-service
  labels:
    app.kubernetes.io/name: slingshot
    app.kubernetes.io/component: webhook-invoker
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: slingshot
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: slingshot-to-rabbitmq
  labels:
    app.kubernetes.io/name: slingshot
    app.kubernetes.io/component: webhook-invoker
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: slingshot
      app.kubernetes.io/component: webhook-invoker
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: rabbitmq
              app.kubernetes.io/component: message-queue
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: slingshot-to-external
  labels:
    app.kubernetes.io/name: slingshot
    app.kubernetes.io/component: webhook-invoker
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: slingshot
      app.kubernetes.io/component: webhook-invoker
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              # localhost
              - 127.0.0.0/8
              # RFC1918 private netblocks
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              # RFC6598 shared netspace
              - 100.64.0.0/10
              # RFC3927 link-local addresses
              - 169.254.0.0/16
              # Multicast
              - 224.0.0.0/4
    - to:
        - ipBlock:
            cidr: ::/0
            except:
              # localhost
              - ::1/128
              # ipv6 private networks (ULA)
              - fc00::/7
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: slingshot-to-apps
  labels:
    app.kubernetes.io/name: slingshot
    app.kubernetes.io/component: webhook-invoker
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: slingshot
      app.kubernetes.io/component: webhook-invoker
  egress:
    - to:
        - namespaceSelector:
            matchLabels: {}
          podSelector:
            matchLabels:
              app.contentgrid.com/service-type: api
      ports:
        - port: 8081 # Access to management port only
