---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solon
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: solon
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: solon
        app.kubernetes.io/component: solon
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        prometheus.io/path: actuator/prometheus
        prometheus.io/port: '8081'
        prometheus.io/scrape: 'true'
        instrumentation.opentelemetry.io/inject-java: grafana-agent/grafana-instrumentation
    spec:
      containers:
        - name: solon
          image: {{ .Values.solon.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          {{- include "contentgrid.resources" (dict "requests" .Values.solon.resourceRequests "limits" .Values.solon.resourceLimits) | nindent 10 }}
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081
          {{ if not .Values.solon.debug -}}
          {{- include "contentgrid.probes" "management" | indent 10 }}
          {{- end }}
          env:
            - name: 'SPRING_CONFIG_IMPORT'
              value: 'file:/etc/solon/application.yml'
            {{ if .Values.solon.debug -}}
            - name: 'JAVA_TOOL_OPTIONS'
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
            {{- end }}
          volumeMounts:
            - name: solon-config-volume
              mountPath: /etc/solon/
              readOnly: true
      volumes:
        - name: solon-config-volume
          configMap:
            name: solon-config
      enableServiceLinks: false
      serviceAccountName: solon-serviceaccount
      automountServiceAccountToken: true
{{ include "nodeSelection" . | indent 6}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: solon-config
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yml: |
    logging:
      level:
        com.contentgrid.solon: DEBUG
    solon:
      kubernetes:
        namespace: {{ .Values.userapps.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: solon-service
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
      app.kubernetes.io/name: solon
  ports:
    - name: http
      port: 8080
      targetPort: http
      appProtocol: http
    - name: management
      port: 8081
      targetPort: management
      appProtocol: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solon-serviceaccount
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: solon-role
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: solon-rolebinding
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: solon-role
subjects:
- kind: ServiceAccount
  name: solon-serviceaccount
  namespace: {{ .Release.Namespace }}
---
{{/* NetworkPolicy solon-to-apiserver */}}
{{- $policyLabels := (list
    "app.kubernetes.io/name: solon"
    "app.kubernetes.io/component: solon"
    "app.kubernetes.io/part-of: contentgrid-runtimeplatform"
    ( printf "app.kubernetes.io/managed-by: %s" .Release.Service)
) | join "\n" | fromYaml -}}
{{- $selectorLabels := (list
      "app.kubernetes.io/name: solon"
      "app.kubernetes.io/component: solon"
) | join "\n" | fromYaml -}}
{{- template "contentgrid.apiserver-network-policy"
      dict
        "name" "solon-to-apiserver"
        "policyLabels" $policyLabels
        "selectorLabels" $selectorLabels
        "rootScope" $ }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: solon-from-opa
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: solon
      app.kubernetes.io/component: solon
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: openpolicyagent
            app.kubernetes.io/component: authorization
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: solon-to-apps
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: solon
      app.kubernetes.io/component: solon
  egress:
    - to:
        - namespaceSelector:
            matchLabels: {}
          podSelector:
            matchLabels:
              app.contentgrid.com/service-type: api
      ports:
        - port: 8081 # Access to management port only
