---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solon
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: solon
  replicas: 1
  template:
    metadata:
      labels:
        {{ if .Values.development -}}
        date: "{{ now | unixEpoch }}"
        {{- end }}
        app.kubernetes.io/name: solon
        app.kubernetes.io/component: solon
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: solon
          image: {{ .Values.solon.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
            - name: http-mgmt
              containerPort: 8081
          env:
            - name: 'SPRING_CONFIG_IMPORT'
              value: 'file:/etc/solon/application.yml'
          volumeMounts:
            - name: solon-config-volume
              mountPath: /etc/solon/
              readOnly: true
      volumes:
        - name: solon-config-volume
          configMap:
            name: solon-config
      serviceAccountName: solon-serviceaccount
      automountServiceAccountToken: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: solon-config
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yml: |
    logging:
      level:
        com.contentgrid.solon: DEBUG
    solon:
      namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: solon-service
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
      app.kubernetes.io/name: solon
  ports:
    - name: http
      port: 8080
      targetPort: http
      appProtocol: http
    - name: mgmt
      port: 8081
      targetPort: http-mgmt
      appProtocol: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solon-serviceaccount
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: solon-role
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  # - deployments
  # - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: solon-rolebinding
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: solon-role
subjects:
- kind: ServiceAccount
  name: solon-serviceaccount
  namespace: {{ .Release.Namespace }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: solon-to-apiserver
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: solon
      app.kubernetes.io/component: solon
  egress:
    - toEntities:
        - kube-apiserver
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: solon-from-opa
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: solon
      app.kubernetes.io/component: solon
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: openpolicyagent
            app.kubernetes.io/component: authorization
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: solon-to-apps
  labels:
    app.kubernetes.io/name: solon
    app.kubernetes.io/component: solon
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: solon
      app.kubernetes.io/component: solon
  egress:
    - to:
        - namespaceSelector:
            matchLabels: {}
          podSelector:
            matchLabels:
              app.contentgrid.com/service-type: api
      ports:
        - port: 8081 # Access to management port only
