{{ if not (default false .Values.surveyor.disabled) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyor-postgres-exporter
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name: postgres-exporter
        app.kubernetes.io/component: surveyor
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-exporter
        app.kubernetes.io/component: surveyor
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        prometheus.io/path: actuator/prometheus
        prometheus.io/port: '8081'
        prometheus.io/scrape: 'true'
        instrumentation.opentelemetry.io/inject-java: grafana-agent/grafana-instrumentation
    spec:
      containers:
        - name: postgres-exporter
          image: {{ .Values.surveyor.postgresExporter.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          {{- if or .Values.surveyor.postgresExporter.resourceLimits .Values.surveyor.postgresExporter.resourceRequests }}
          resources:
            {{- with .Values.surveyor.postgresExporter.resourceLimits }}
            limits:
              cpu: {{ .cpu }}
              memory: {{ .memory }}
            {{- end }}
            {{- with .Values.surveyor.postgresExporter.resourceRequests }}
            requests:
              cpu: {{ .cpu }}
              memory: {{ .memory }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081
          {{ if not .Values.surveyor.postgresExporter.debug -}}
          {{- include "contentgrid.probes" "management" | indent 10 }}
          {{- end }}
          env:
            - name: 'MANAGEMENT_SERVER_PORT'
              value: '8081'
            - name: 'SURVEYOR_EXPORTER_KUBERNETES_NAMESPACE'
              value: '{{ .Values.userapps.namespace }}'
            {{ if .Values.surveyor.postgresExporter.debug -}}
            - name: 'JAVA_TOOL_OPTIONS'
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
            {{- end }}
      enableServiceLinks: false
      serviceAccountName: surveyor-postgres-exporter-serviceaccount
      automountServiceAccountToken: true
{{ include "nodeSelection" . | indent 6}}
---
apiVersion: v1
kind: Service
metadata:
  name: surveyor-postgres-exporter
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: surveyor
  ports:
    - name: http
      port: 80
      targetPort: http
      appProtocol: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: surveyor-postgres-exporter-serviceaccount
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: surveyor-postgres-exporter-role
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: surveyor-postgres-exporter-rolebinding
  namespace: {{ .Values.userapps.namespace }}
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: surveyor-postgres-exporter-role
subjects:
- kind: ServiceAccount
  name: surveyor-postgres-exporter-serviceaccount
  namespace: {{ .Release.Namespace }}
---
{{/* NetworkPolicy surveyor-postgres-exporter-to-apiserver */}}
{{- $policyLabels := (list
    "app.kubernetes.io/name: postgres-exporter"
    "app.kubernetes.io/component: surveyor"
    "app.kubernetes.io/part-of: contentgrid-runtimeplatform"
    ( printf "app.kubernetes.io/managed-by: %s" .Release.Service)
) | join "\n" | fromYaml -}}
{{- $selectorLabels := (list
    "app.kubernetes.io/name: postgres-exporter"
    "app.kubernetes.io/component: surveyor"
) | join "\n" | fromYaml -}}
{{- template "contentgrid.apiserver-network-policy"
      dict
        "name" "surveyor-postgres-exporter-to-apiserver"
        "policyLabels" $policyLabels
        "selectorLabels" $selectorLabels
        "rootScope" $ }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: surveyor-postgres-exporter-from-prometheus
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter
      app.kubernetes.io/component: surveyor
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
              app.kubernetes.io/component: surveyor

{{ if .Values.userapps.database }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: surveyor-postgres-exporter-to-database
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter
      app.kubernetes.io/component: surveyor
  egress:
    {{ range $db := .Values.userapps.database }}
    - to:
        - ipBlock:
            cidr: {{ $db.ip }}/24
      ports:
        - port: {{ $db.port }}
    {{ end }}
{{ end }}
{{ end }}