{{ if .Values.surveyor.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyor-cgapp-api-exporter
  labels:
    app.kubernetes.io/name: cgapp-api-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name: cgapp-api-exporter
        app.kubernetes.io/component: surveyor
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cgapp-api-exporter
        app.kubernetes.io/component: surveyor
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        prometheus.io/path: actuator/prometheus
        prometheus.io/port: '8081'
        prometheus.io/scrape: 'true'
        instrumentation.opentelemetry.io/inject-java: grafana-agent/grafana-instrumentation
    spec:
      containers:
        - name: cgapp-api-exporter
          image: {{ .Values.surveyor.cgappApiExporter.image }}
          {{ if .Values.development -}}
          imagePullPolicy: Always
          {{- end }}
          {{- if or .Values.surveyor.cgappApiExporter.resourceLimits .Values.surveyor.cgappApiExporter.resourceRequests }}
          resources:
            {{- with .Values.surveyor.cgappApiExporter.resourceLimits }}
            limits:
              cpu: {{ .cpu }}
              memory: {{ .memory }}
            {{- end }}
            {{- with .Values.surveyor.cgappApiExporter.resourceRequests }}
            requests:
              cpu: {{ .cpu }}
              memory: {{ .memory }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081
          {{ if not .Values.surveyor.cgappApiExporter.debug -}}
          {{- include "contentgrid.probes" "management" | indent 10 }}
          {{- end }}
          env:
            - name: 'SPRING_CONFIG_IMPORT'
              value: 'file:/etc/surveyor/application.yml,configtree:/etc/surveyor/*/'
            {{ if .Values.surveyor.cgappApiExporter.debug -}}
            - name: 'JAVA_TOOL_OPTIONS'
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
            {{- end }}
          volumeMounts:
            - name: surveyor-config-volume
              mountPath: /etc/surveyor/
              readOnly: true
            - name: rabbitmq-config
              mountPath: /etc/surveyor/rabbitmq
      volumes:
        - name: surveyor-config-volume
          configMap:
            name: surveyor-cgapp-api-exporter-config
        - name: rabbitmq-config
          secret:
            secretName: surveyor-cgapp-api-exporter-rabbitmq
      enableServiceLinks: false
      automountServiceAccountToken: false
{{ include "nodeSelection" . | indent 6}}
---
apiVersion: v1
kind: Service
metadata:
  name: surveyor-cgapp-api-exporter
  labels:
    app.kubernetes.io/name: cgapp-api-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: cgapp-api-exporter
    app.kubernetes.io/component: surveyor
  ports:
    - name: http
      port: 8080
      targetPort: http
      appProtocol: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: surveyor-cgapp-api-exporter-config
  labels:
    app.kubernetes.io/name: cgapp-api-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yml: |
    management:
      server:
        port: 8081
    logging.level:
      com.contentgrid.surveyor: INFO
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: surveyor-cgapp-api-exporter-to-rabbitmq
  labels:
    app.kubernetes.io/name: cgapp-api-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cgapp-api-exporter
      app.kubernetes.io/component: surveyor
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: rabbitmq
              app.kubernetes.io/component: message-queue
              app.kubernetes.io/part-of: contentgrid-runtimeplatform
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: surveyor-cgapp-api-exporter-from-prometheus
  labels:
    app.kubernetes.io/name: cgapp-api-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cgapp-api-exporter
      app.kubernetes.io/component: surveyor
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
              app.kubernetes.io/component: surveyor
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: surveyor-cgapp-api-exporter-rabbitmq
  labels:
    app.kubernetes.io/name: cgapp-api-exporter
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.rabbitmq.enabled }}
stringData:
  spring.rabbitmq.host: {{ include "rabbitmq_host" .}}
  spring.rabbitmq.username: surveyor
  #spring.rabbitmq.password: Set by rabbitmq bootstrap
  surveyor.exporter.rabbitmq.queue: contentgrid.surveyor.cgapp-api-exporter
  surveyor.exporter.rabbitmq.enabled: 'true'
{{- end }}