---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: surveyor-prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: "surveyor-prometheus"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: surveyor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/component: surveyor
        app.kubernetes.io/part-of: contentgrid-runtimeplatform
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        prometheus.io/path: metrics
        prometheus.io/port: '9090'
        prometheus.io/scrape: 'true'
    spec:
      initContainers:
        - name: "init-chown-data"
          image: "busybox"
          # 65534 is the nobody user that prometheus uses.
          command: ["chown", "-R", "65534:65534", "/data"]
          volumeMounts:
            - name: tsdb-storage
              mountPath: /data
      containers:
        - name: prometheus
          image: {{ .Values.surveyor.prometheus.image }}
          ports:
            - name: management
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: management
          readinessProbe:
            httpGet:
              path: /-/ready
              port: management
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.retention.time=24h
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
              readOnly: true
            - name: tsdb-storage
              mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: surveyor-prometheus-config
        - name: tsdb-storage
          persistentVolumeClaim:
            claimName: surveyor-prometheus-tsdb
      enableServiceLinks: false
      automountServiceAccountToken: false
  volumeClaimTemplates:
    - metadata:
        name: tsdb-storage
        labels:
          app.kubernetes.io/name: prometheus
          app.kubernetes.io/component: surveyor
          app.kubernetes.io/part-of: contentgrid-runtimeplatform
          app.kubernetes.io/managed-by: {{ .Release.Service }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        {{- with .Values.surveyor.prometheus.storageClassName }}
        storageClassName: {{ . }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: surveyor-prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: surveyor
  ports:
    - name: http
      port: 80
      targetPort: management
      appProtocol: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: surveyor-prometheus-config
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 5m
      scrape_timeout: 1m
      evaluation_interval: 5m
    scrape_configs:
      - job_name: database
        static_configs:
          - targets:
              - surveyor-postgres-exporter
      - job_name: "cgapp_api"
        static_configs:
          - targets:
              - surveyor-cgapp-api-exporter:8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: surveyor-prometheus-to-postgres-exporter
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: surveyor
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgres-exporter
              app.kubernetes.io/component: surveyor
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: surveyor-prometheus-to-cgapp-api-exporter
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: surveyor
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: cgapp-api-exporter
              app.kubernetes.io/component: surveyor
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: surveyor-prometheus-from-pegman
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: surveyor
    app.kubernetes.io/part-of: contentgrid-runtimeplatform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: surveyor
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: pegman
              app.kubernetes.io/component: surveyor
