{{ range $name, $settings := .Values.certificates.issuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $name }}
spec:
  acme:
    email: {{ $settings.acme.email }}
    server: {{ $settings.acme.server }}
    {{- with $settings.acme.externalAccountBinding }}
    externalAccountBinding:
      keyID: {{ .keyId }}
      keySecretRef:
        name: {{ .secretName }}
        key: eab-credentials
    {{- end }}
    privateKeySecretRef:
      name: {{ .$name }}-accountkey
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
{{ end }}
