name: 'Integration Tests'
on:
  push:

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest-8-cores
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
          cache: gradle
      - name: Test
        run: ./gradlew check --info -PdisableDockerRegistryCache=true
  publish:
    needs: [build]
    name: publish
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package & publish
        run: |
          chart_version=${GITHUB_REF#refs/tags/v}
          helm package contentgrid-rtp-helm --dependency-update --version "$chart_version"
          helm publish "contentgrid-rtp-helm-${chart_version}.tgz" oci://ghcr.io/xenit-eu
