name: 'Integration Tests'
on:
  push:


defaults:
  run:
    working-directory: ./test

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
          cache: gradle
      - name: Login to docker.contentgrid.com
        run: echo "${{ secrets.CLOUDSMITH_APIKEY }}" | docker login docker.contentgrid.com --username "${{ secrets.CLOUDSMITH_USER }}" --password-stdin
      - name: Test
        run: ./gradlew check --info -PdisableDockerRegistryCache=true

